/*----- PROTECTED REGION ID(DishManager::DynAttrUtils.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        DishManagerDynAttrUtils.cpp
//
// description : Dynamic attributes utilities file for the DishManager class
//
// project :     DishManager
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <DishManager.h>
#include <DishManagerClass.h>

/*----- PROTECTED REGION END -----*/	//	DishManager::DynAttrUtils.cpp

//================================================================
//  Attributes managed is:
//================================================================
//================================================================

//	For compatibility reason, this file (DishManagerDynAttrUtils)
//	manage also the dynamic command utilities.
//================================================================
//  The following table gives the correspondence
//  between command and method names.
//
//  Command name  |  Method name
//================================================================
//  dummyDynCmd   |  dummy_dyn_cmd
//================================================================

namespace DishManager_ns
{
//=============================================================
//	Add/Remove dynamic attribute methods
//=============================================================



//============================================================
//	Tool methods to get pointer on attribute data buffer 
//============================================================


//=============================================================
//	Add/Remove dynamic command methods
//=============================================================

//--------------------------------------------------------
/**
 *	Add a dummyDynCmd dynamic command.
 *
 *  parameter cmdname: command name to be cretated and added.
 *  parameter device:  Set this flag to true if the command must be added for only this device.
 */
//--------------------------------------------------------
void DishManager::add_dummyDynCmd_dynamic_command(string cmdname, bool device)
{
	dummyDynCmdClass	*pdummyDynCmdCmd =
		new dummyDynCmdClass(cmdname.c_str(),
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::EXPERT);
	add_command(pdummyDynCmdCmd, device);
}
//--------------------------------------------------------
/**
 *	remove a dummyDynCmd dynamic command.
 *
 *  parameter cmdname: command name to be removed.
 */
//--------------------------------------------------------
void DishManager::remove_dummyDynCmd_dynamic_command(string cmdname)
{
	remove_command(cmdname, true);
}

} //	namespace
