# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX_OS='ubuntu/xenial64'
BOX_RAM="4096"
BOX_SSH_FW_PORT="2223"
BOX_NAME='Ubuntu16_04Box'
BOX_HOSTNAME='ska-lmc-vm'
BOX_VAGRANT_USER='ubuntu'

## Set the password with "mkpasswd --method=sha-512"
BOX_ADMIN_USER='admin'
BOX_ADMIN_USER_PASS='$6$SHYfyC9Bh4J5PS3$jURFzkmQ40o1.NBlkUSp0Zr3sxuPvecFqMalt.LqVpmzOeiPW/.WxmPlA7IGfCNjqqBZv8Ol.2EyODE0coJJs.' ## admin$16
BOX_TEST_USER='skaci'
##BOX_TEST_USER_PASS='$6$HB3Er5LuJmhg.0AD$GZxjay54KobkaH4qfdZxCAv5JLjjtbx5cz.v9Yenq78NKXBoj2xCugZms9fCj7kQ6RCnGQ.JnHAGBWDD3ohsz1' ## jenkins
BOX_USER='ska'
BOX_USER_PASS='ska'

ANSIBLE_PROVISION_FILE='setup_vmbox.yml'

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = BOX_OS

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  config.vm.network "forwarded_port", guest: 22, host: BOX_SSH_FW_PORT, id: 'ssh'

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

	#config.vm.ssh.keep_alive = true

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  
  config.vm.provider "virtualbox" do |vb|
  		# Display the VirtualBox GUI when booting the machine
     	vb.gui = false
  
     	# Customize the amount of memory on the VM:
     	vb.memory = BOX_RAM

			# Define vm name
			vb.name = BOX_NAME
 	end
  

	# Disable the new default behavior introduced in Vagrant 1.7, to
  # ensure that all Vagrant machines will use the same SSH key pair.
  # See https://github.com/mitchellh/vagrant/issues/5005
	# NB: For some reasons this creates problem in ssh connection to default vagrant user. Don't use it!!!
  #config.ssh.insert_key = false


  ### Set up Ansible provisioning
	config.vm.provision "ansible" do |p|
    p.playbook   = ANSIBLE_PROVISION_FILE
    p.verbose    = true
    p.extra_vars =
        {
						ansible_ssh_user: BOX_VAGRANT_USER,
						ansible_ssh_port: BOX_SSH_FW_PORT,
						box_hostname: BOX_HOSTNAME,
						box_admin_user: BOX_ADMIN_USER,
						box_admin_user_pass: BOX_ADMIN_USER_PASS,
            box_test_user: BOX_TEST_USER,
						box_user: BOX_USER,
						box_user_pass: BOX_USER_PASS
        }
  end

end
