---

- hosts: lmc_servers
  gather_facts: true

  vars_prompt:
    - name: "prompted_mysql_root_pass"
      prompt: "Enter mysql root password"
      private: yes

  pre_tasks:
    
    - name: Source environment in bashrc file
      shell: "{{ item }}"
      args:
        executable: /bin/bash
      with_items:
        - source ~/.bashrc
    - shell: echo {{ ansible_env.TANGO_HOST}}   
      when: "'TANGO_HOST' in ansible_env"
      

  roles:
  - { role: bootstrap, tags: bootstrap }
  - { role: common, tags: install_packages }	
  - { role: setup, tags: install_packages }
  - { role: deploy_lmc, tags: deploy }
  - { role: configure_lmc, tags: configure }

...
