PKG_CHECK_MODULES(PC_ZMQ libzmq)

## Headers
FIND_PATH (
	ZMQ_INCLUDE_DIR
	NAMES zmq.h
  HINTS ${PC_ZMQ_INCLUDE_DIRS} $ENV{ZMQ_ROOT}/include 
	PATHS ${PC_ZMQ_INCLUDE_DIRS} $ENV{ZMQ_ROOT}/include /usr/local/include /usr/include
)


## Libraries
#FIND_LIBRARY(
#	ZMQ_LIBRARIES
#  NAMES zmq
#  HINTS ${PC_ZMQ_LIBRARY_DIRS} $ENV{ZMQ_ROOT}/lib
#  PATHS ${PC_ZMQ_LIBRARY_DIRS} $ENV{ZMQ_ROOT}/lib 
#/usr/local/lib /usr/local/lib64 /usr/lib /usr/lib64
#)

FIND_LIBRARY(
	ZMQ_LIBRARY
  NAMES zmq
  HINTS ${PC_ZMQ_LIBRARY_DIRS} $ENV{ZMQ_ROOT}/lib
  PATHS ${PC_ZMQ_LIBRARY_DIRS} $ENV{ZMQ_ROOT}/lib 
#/usr/local/lib /usr/local/lib64 /usr/lib /usr/lib64
)

set ( ZMQ_LIBRARIES ${ZMQ_LIBRARY} )
set ( ZMQ_INCLUDE_DIRS ${ZMQ_INCLUDE_DIR} )

INCLUDE(FindPackageHandleStandardArgs)
#FIND_PACKAGE_HANDLE_STANDARD_ARGS(ZMQ DEFAULT_MSG ZMQ_LIBRARIES ZMQ_INCLUDE_DIRS)
#MARK_AS_ADVANCED(ZMQ_LIBRARIES ZMQ_INCLUDE_DIRS)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(ZMQ DEFAULT_MSG ZMQ_LIBRARY ZMQ_INCLUDE_DIR)
MARK_AS_ADVANCED(ZMQ_LIBRARIES ZMQ_INCLUDE_DIRS)
